### ISSUE TITLE
Dashboard for School Administrator Page(Website and Mobile)

### ISSUE THREAD

**Issue by Pyreshy** [zuri-training/Project-Mydebtor-Team-40#10]

**Comment by symplymarve** [comment]
Wireframe and Lo-fi done

**Comment by michaelbabajide** [comment]
Helped in revamping the dashboard

**Comment by symplymarve** [comment]
Desktop View for Dashboard has been completed. I have to replace some of the wireframes and lofi because of the changes made

**Comment by symplymarve** [comment]
@Pyreshy the Hifi for the Debtor page, admin View is completed. Kindly Check on the figma moodboard. 
@Zion-El I am done with the desktop view for the Admin Dashboards. Sorry for the inconvenience

**Comment by Pyreshy** [comment]
Seen, Good Job marvelous!

**Comment by symplymarve** [comment]
https://www.figma.com/file/j8hznqDDMZwr8FPzXvUv8g/Team-40-_My-Debtors(-Studebt)?node-id=2085%3A27064
For Admin Dashboard first screen. Done with @michaelbabajide and @SAINt-Oliverrr

**Comment by symplymarve** [comment]
https://www.figma.com/file/j8hznqDDMZwr8FPzXvUv8g/Team-40-_My-Debtors(-Studebt)?node-id=2343%3A39680
for Admin Desktop Dashboard Add Debtor Second screen done with @SAINt-Oliverrr

**Comment by symplymarve** [comment]
https://www.figma.com/file/j8hznqDDMZwr8FPzXvUv8g/Team-40-_My-Debtors(-Studebt)?node-id=2306%3A30283

for Admin Desktop Dashboard add debtor screen all done.

**Comment by symplymarve** [comment]
https://www.figma.com/file/j8hznqDDMZwr8FPzXvUv8g/Team-40-_My-Debtors(-Studebt)?node-id=2011%3A23875
https://www.figma.com/file/j8hznqDDMZwr8FPzXvUv8g/Team-40-_My-Debtors(-Studebt)?node-id=2371%3A100147

For Admin Desktop Dashboard Information hub done with @SAINt-Oliverrr

**Comment by symplymarve** [comment]
https://www.figma.com/file/j8hznqDDMZwr8FPzXvUv8g/Team-40-_My-Debtors(-Studebt)?node-id=2011%3A28304
https://www.figma.com/file/j8hznqDDMZwr8FPzXvUv8g/Team-40-_My-Debtors(-Studebt)?node-id=2021%3A30188
https://www.figma.com/file/j8hznqDDMZwr8FPzXvUv8g/Team-40-_My-Debtors(-Studebt)?node-id=2011%3A25998
https://www.figma.com/file/j8hznqDDMZwr8FPzXvUv8g/Team-40-_My-Debtors(-Studebt)?node-id=2011%3A28214

For Admin Desktop Dashboard Private messaging

**Comment by symplymarve** [comment]
https://www.figma.com/file/j8hznqDDMZwr8FPzXvUv8g/Team-40-_My-Debtors(-Studebt)?node-id=2343%3A37005
https://www.figma.com/file/j8hznqDDMZwr8FPzXvUv8g/Team-40-_My-Debtors(-Studebt)?node-id=2343%3A37756
https://www.figma.com/file/j8hznqDDMZwr8FPzXvUv8g/Team-40-_My-Debtors(-Studebt)?node-id=2343%3A38617
https://www.figma.com/file/j8hznqDDMZwr8FPzXvUv8g/Team-40-_My-Debtors(-Studebt)?node-id=2424%3A39003

Contenders page done

**Comment by symplymarve** [comment]
https://www.figma.com/file/j8hznqDDMZwr8FPzXvUv8g/Team-40-_My-Debtors(-Studebt)?node-id=2197%3A30112
https://www.figma.com/file/j8hznqDDMZwr8FPzXvUv8g/Team-40-_My-Debtors(-Studebt)?node-id=2451%3A39275
https://www.figma.com/file/j8hznqDDMZwr8FPzXvUv8g/Team-40-_My-Debtors(-Studebt)?node-id=2439%3A38370

Admin Dashboard Mobile View for Information Hub View more, Messages default and Debtors Information all done.

**Comment by symplymarve** [comment]
Prototype all done. Prototype overlay linked to settings page and admin profile that was done by other members of the team.
