### ISSUE TITLE
Dashboard for user/Student profile/Complaint Page (Website and Mobile)

### ISSUE THREAD

**Issue by Pyreshy** [zuri-training/Project-Mydebtor-Team-40#13]

**Comment by Pyreshy** [comment]
Done.

**Comment by michaelbabajide** [comment]
Designed by: @SAINt-Oliverrr & @michaelbabajide 
Dashboard Home Screen(Desktop): https://www.figma.com/file/j8hznqDDMZwr8FPzXvUv8g/Team-40-_My-Debtors(-Studebt)?node-id=2085%3A27064

Dashboard Home Screen(Mobile): https://www.figma.com/file/j8hznqDDMZwr8FPzXvUv8g/Team-40-_My-Debtors(-Studebt)?node-id=2185%3A33166
