### ISSUE TITLE
Post/Comment / How it works Page (Website and Mobile)

### ISSUE THREAD

**Issue by Pyreshy** [zuri-training/Project-Mydebtor-Team-40#6]

**Comment by ifuvivezenwanne** [comment]
Task received.
Task was done with a team member (Zainab for  the Lo-fi)
Task was completed on Tuesday, 2nd of August, 2022.

**Comment by Pyreshy** [comment]
Good Job vivian

**Comment by ifuvivezenwanne** [comment]
HOW IT WORKS PAGE (High Fidelity) Desktop view - https://www.figma.com/file/j8hznqDDMZwr8FPzXvUv8g/Team-40-_My-Debtors(-Studebt)?node-id=1840%3A21930

HOW IT WORKS PAGE (High Fidelity) Mobile view - https://www.figma.com/file/j8hznqDDMZwr8FPzXvUv8g/Team-40-_My-Debtors(-Studebt)?node-id=1840%3A21954

**Comment by ovayoza** [comment]
Provided Content & co-designed the page with a team member; Vivian
Web view: https://www.figma.com/file/j8hznqDDMZwr8FPzXvUv8g/Team-40-_My-Debtors(-Studebt)?node-id=984%3A11760
Mobile view: https://www.figma.com/file/j8hznqDDMZwr8FPzXvUv8g/Team-40-_My-Debtors(-Studebt)?node-id=990%3A11840
